baseURL = "http://sandeshdamkondwar.github.io/"
languageCode = "en-us"
title = "Sandesh Damkondwar"
theme = "noteworthy"
publishDir = "docs"

[params]
    # Main
    email = "sandeshdamkondwar@gmail.com"
    twitter = "https://twitter.com/sandydamy"
    pinterest = "https://in.pinterest.com/sandydamy"
    linkedin = "http://linkedin.com/in/sandeshdamkondwar"